version: '3'

volumes:
  postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: events_django
    container_name: events_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    environment:
      USE_DOCKER: "yes"
      IPYTHONDIR: /app/.ipython
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
    ports:
      - "8000:8000"
    command: /start-app.sh

  postgres:
    image: postgres:12.3
    container_name: events_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api

  # docs:
  #   image: app_local_docs
  #   container_name: docs
  #   build:
  #     context: .
  #     dockerfile: ./docker/docs/Dockerfile
  #   env_file:
  #     - ./.envs/.local/.django
  #   volumes:
  #     - ./docs:/docs:z
  #     - ./config:/app/config:z
  #     - ./app:/app/app:z
  #   ports:
  #     - "7000:7000"
  #   command: /start-docs
